/** City keys and district slugs used by the analyze form and Supabase city/district fields. */
export const LOCATION_MAP: Record<string, string[]> = {
  "jakarta selatan": [
    "kebayoran baru",
    "pondok indah",
    "cipete",
    "fatmawati",
    "tebet",
    "kemang",
    "jagakarsa",
  ],
  "jakarta barat": [
    "kebon jeruk",
    "tanjung duren",
    "cengkareng",
    "kalideres",
    "puri indah",
  ],
  "jakarta timur": ["duren sawit", "cakung", "cipinang"],
  "jakarta utara": ["kelapa gading", "pluit", "pantai indah kapuk"],
  "jakarta pusat": ["menteng", "senen", "tanah abang"],
  "tangerang selatan": [
    "bintaro",
    "graha bintaro",
    "bsd",
    "bsd city",
    "gading serpong",
    "alam sutera",
    "serpong",
    "ciputat",
    "pamulang",
  ],
  tangerang: ["karawaci", "cikupa", "tigaraksa"],
  bekasi: [
    "bekasi barat",
    "bekasi timur",
    "bekasi utara",
    "bekasi selatan",
    "grand galaxy",
    "harapan indah",
  ],
  depok: ["cinere", "beji", "margonda", "sawangan"],
  bogor: ["sentul", "sentul city", "cibinong", "bogor selatan"],
};
